### ISSUE TITLE
Building a CSS tricks website clone with Webiny and NextJS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#10]
Introduction

The numerous benefits and simplicity of Headless Content Management Systems are the topmost reasons why anyone will choose it for building modern application. Alot of CMS exist today that solve problems associated with managing contents across multiple platforms but only a few of them comes with needed perks such as easy scalability, data privacy, less cost in running & maintenance and easy to adapt. Webiny gives that much needed perks for scaling headless CMS.

Aim

This article aims at introducing you to headless CMS as well as teaching you how to build a serverless blog using NextJS and Webiny. It will also expose you to the need to adopt a serverless approach in building modern applications.

Outline

- Introduction to headless CMS
- Why Webiny?
- Requirements
- Setting up and configuring a Webiny project
- Configuration GraphQL API
- Performing CRUD operations
- Conclusion

**Comment by EmmanuelTheCoder** [comment]
So that I get it well, the task is to clone css-tricks.com using Webiny and NextJS, right?

**Comment by endymion1818** [comment]
@EmmanuelTheCoder Yes that's correct

**Comment by EmmanuelTheCoder** [comment]
Thanks. Will send in the brief shortly.

**Comment by EmmanuelTheCoder** [comment]
@endymion1818 Thanks. Will send in the brief shortly.

**Comment by EmmanuelTheCoder** [comment]
## Introduction

The numerous benefits and simplicity of Headless Content Management Systems are the topmost reasons why anyone will choose it for building modern application. Alot of CMS exist today that solve problems associated with managing contents across multiple platforms but only a few of them comes with needed perks such as easy scalability, data privacy, less cost in running & maintenance and easy to adapt. Webiny gives that much needed perks for scaling headless CMS.

## Aim

This article aims at introducing you to headless CMS as well as teaching you how to build a serverless blog using NextJS and Webiny. It will also expose you to the need to adopt a serverless approach in building modern applications.

## Outline

* Introduction to headless CMS
* Why Webiny?
* Requirements
* Setting up and configuring a Webiny project
* Configuration GraphQL API
* Performing CRUD operations
* Conclusion

@endymion1818 Here is the brief for the article
