### ISSUE TITLE
[SUBMIT] Benefits of using headless cms as a developer

### ISSUE THREAD

**Issue by popoolatopzy** [webiny/write-with-webiny#102]
### Introduction

Building and maintaining applications can be overwhelming as it requires a lot of time, effort, and techniques to build both the backend and front end from scratch. But with headless CMS, developers have to focus less on the backend. This article will explore some benefits of using a headless CMS like Webiny as a developer.

### Goals

This article aims to inform the readers of the benefits of using headless CMS as their application backend.

### Outline

[Here is the sample outline.
 -  Introduction
 - Overview of headless CMS
 - What is webiny
 - Webiny Installation
  - Benefits of  using  headless cms as a developer
 -- Cross-platform Content Sharing
 --  SEO Optimization
 -- Less maintenance
 -- Effective Team workflow
 -- SEO Optimization
 -- User-Friendly
 -- Jamstick technology
 -- Plugin 
  - Conclusion
  - Resources]

### Sample articles

https://strapi.io/blog/boosting-productivity-with-strapi-plugins?utm_campaign=Strapi%20Blog&utm_source=devto&utm_medium=blog

https://strapi.io/blog/webhooks

https://dev.to/popoolatopzy/connecting-node-js-with-mysql-database-36dh

**Comment by kilokomuli** [comment]
I would like to do this.

**Comment by endymion1818** [comment]
Thanks for your submission @popoolatopzy, we'll consider it and let you know! Please send me a message via Slack so we can get you set up on the writer program 😄 

@kilokomuli as this is a suggestion from @popoolatopzy, I'm going to assign it to them. We'd be super happy if you can do some research and suggest another topic. Thanks!

**Comment by popoolatopzy** [comment]
Alright, Thank you @endymion1818

**Comment by endymion1818** [comment]
Thanks for the suggestion, as per our conversation on Slack, we agreed to close this one. Though please do submit another topic!
