### ISSUE TITLE
Create a personal blog using Hugo and Webiny

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#11]

**Comment by pradeephubgit** [comment]
A high-level overview of this task could be the following:

1. Create a site using Hugo with one of the available themes, and add blog content to it. To ensure better control and privacy for the personal blog, instead of hosting it in the Hugo server, go to Step 2.
2. Host the blog through Webiny's CMS (Self-hosting). 

Please let me know if more details are required. I will research and add them.

**Comment by EmmanuelTheCoder** [comment]
I'd love to be assigned this task.

**Comment by endymion1818** [comment]
Sorry @EmmanuelTheCoder, since @pradeephubgit was the first to submit a brief for this article we are going to ask them to write this article. We'd be super happy if you could pick any other article with a "looking for a writer" label, or you could submit your idea.

**Comment by pradeephubgit** [comment]
Thanks for the clarification, @endymion1818 . I will start my task today. Again, thanks to you, @swapnilmmane  and the Webiny team for the writing opportunity.

**Comment by EJINEROZ** [comment]
If by any chance I’d love to be assigned this topic if it’s still open.

**Comment by swapnilmmane** [comment]
Thank you @EJINEROZ for your interest. Could you please share the brief and topics that you are planning for this article and also some of your sample articles, thank you!

**Comment by EJINEROZ** [comment]
@swapnilmmane 
1. Introduction To Hugo and Webiny CMS
2.Basic setup of both Hugo and Webiny
3.Create Static Hugo website and add content to it(brief intro to Hugo theme)
4.Integrate Hugo to Webiny CMS
5.Exemplary Post on Hugo website
6.Deployment
7.Conclusion

**Comment by swapnilmmane** [comment]
Thank you, @EJINEROZ, for sharing it. It would be great if you could include a little elaborative outline, especially could you please elaborate these two points more 
> 4.Integrate Hugo to Webiny CMS
> 5.Exemplary Post on Hugo website

Also, it will be great to include the blog listing and blog details page. And allow users to filter articles by author, thanks!

Could you please also share some of your previous written articles.

**Comment by EmmanuelTheCoder** [comment]
Hi @endymion1818  @swapnilmmane 

Can I take this?

**Comment by AmenyaZ** [comment]
Hello, @endymion1818  @swapnilmmane I would love to work on this. Can I?

**Comment by endymion1818** [comment]
Hey Zaccheus! Join us in the community and send me a message, we'll chat more there!
