### ISSUE TITLE
Build a Blog using Astro Authoring and Webiny CMS

### ISSUE THREAD

**Issue by Claradev32** [webiny/write-with-webiny#115]
### Introduction

In this tuorial the reader will learn how to build a blog application using the Astrojs authorig integration. They will learn how to setup a Webiny account to store the blog records. 

### Goals

In this article, we will learn about the Webiny CMS and how we can use it in an Astrojs application by working on building a Blog app.

### Outline

  - What is a Headless CMS?
  - Why use Webiny CMS?
  - Building a To-Do application?
    -- Installing dependencies
    -- Creating an input section
    -- Add To-Do list display
  - Setting up Webiny CMS
    -- Content Structure
    -- Connecting the CMS to the application
  - Setup Project
  - Install Dependencies
  - Create Components
  - Create Markdown Pages
  - Create a Layout
  - Use Frontmatter
  - Final Result
  - Conclusion
  - Resources

### Sample articles

https://blog.openreplay.com/building-a-react-app-with-vite
https://blog.openreplay.com/creating-a-theme-in-gatsby-with-stitches
https://blog.openreplay.com/build-a-lightweight-web-component-with-lit-js
https://blog.openreplay.com/beautiful-ui-components-with-nextui
https://blog.openreplay.com/static-website-using-ilesjs-and-vue

**Comment by Claradev32** [comment]
@endymion1818 
I wish to write on this topic.

**Comment by endymion1818** [comment]
Hi @Claradev32 thanks for the submission 🤔 This is an interesting prospect, what were you planning to use for the client-side JS? React, Vue or something else?

**Comment by Claradev32** [comment]
Hi @endymion1818 , Astrojs is a web framework on it's own. So I'm using Astro on the client side and Webiny on the server side.

**Comment by endymion1818** [comment]
Thanks for your submission @Claradev32, this is too similar to an article we published recently: https://www.webiny.com/blog/build-blog-astro-webiny-headless-cms.
