### ISSUE TITLE
[SUBMIT] Using Tensei.js Headless CMS To Build And Deploy A Forums App API And CMS

### ISSUE THREAD

**Issue by Geo-free** [webiny/write-with-webiny#122]
### Introduction

Tensei.js is a node.js  Headless CMS for building powerful, secure, and flexible backend APIs for applications. In this article, we will be building a basic API and administration panel for a simple forum application. Tensei.js also comes with a system built in for all business needs, for example, sending and replying to emails, in-app chats.

### Goals

 In this article, we will learn about Tensei.js and how we can use it to build flexible, powerful, and secure APIs for our  applications.
 

### Outline

   - What Is Tensei.js
  - Installing Tensei
  - Building a Sample Application
  - GraphQl Demo
  - Deployment
  - Conclusion
  - Resources

**Comment by endymion1818** [comment]
Hi @Geo-free, thanks for your submission! How does your topic relate to Webiny Headless CMS?

**Comment by Geo-free** [comment]
Hi @endymion1818, thanks for getting in touch on this topic, now, Tensei.js is a rich, open-source headless CMS that makes it extremely quick and straightforward to assemble powerful and secure APIs. In this topic, I will be centering my article content only on Tensei.js. Out of the box, you can setup a fully customizable GraphQL or Rest API with email and password and social authentication, JWT, access and refresh tokens, Role Based Access Control  and a beautiful, fully customizable headless CMS dashboard to manage your content seamlessly using Tensei.js

**Comment by swapnilmmane** [comment]
Sorry, @Geo-free seems this topic is not in line with our Write with Webiny program. We are only accepting articles where the authors build something on top of Webiny CMS. Thanks!
