### ISSUE TITLE
Build a Blog with Gatsby and Webiny Headless CMS

### ISSUE THREAD

**Issue by swapnilmmane** [webiny/write-with-webiny#14]

**Comment by fabulousDesigns** [comment]
A headless CMS keeps data in a backend database, but in contrast to a standard CMS service, where the information is displayed using a predefined template, the content is given via an API, giving developers the freedom to consume the data across different clients or frontend frameworks.
Webiny is one such instance of a headless CMS. Its serverless headless CMS offers a customized admin application for content creation as well as a powerful GraphQL API for consuming the material generated by the admin application. The administration app will be used to model content through the headless CMS app later in this article. The content will then be consumed via the GraphQL API in a Gatsby blog application.

**Comment by endymion1818** [comment]
@fabulousDesigns Hey, I've reached out to you on the community slack channel, let's talk more there!

**Comment by endymion1818** [comment]
Hi @fabulousDesigns, we need you to sign a freelance writer agreement with us, as a matter of urgency could you please contact me via Slack and we'll get you set up. Thanks!

**Comment by endymion1818** [comment]
Hey @fabulousDesigns, thanks for sending us your content! Could you sign the scope of works? We won't be able to publish it before we have that signed document.

**Comment by kaf-lamed-beyt** [comment]
Hi @endymion1818
