### ISSUE TITLE
Build a blog with Astro and Webiny Headless CMS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#15]
In this article, the reader will know what is Webiny. They will also learn how to set up Webiny with Astro. In addition, they will learn to source data from our Webiny Headless CMS to our frontend (Astro). We will be building a Blog with Astro, Webiny Headless CMS and TailwindCSS.

Outline:

- Introduction
- What we are building: Blog
- What is Webiny?
- Benefits of using Webiny
- What is Astro?
- Benefits of using Astro
- Prerequisites
- Setting up our Webiny Headless CMS
- Creating our models
- - Authors
- - Posts
- Adding content
- Using the GraphQL API
- Setting up Roles and Permissions
- Setting up our Frontend with Astro
- Configuring our dependencies: TailwindCSS
- Fetching data from Webiny
- Building our application UI with Astro and TailwindCSS
- Conclusion

**Comment by am-miracle** [comment]
Hi @endymion1818 

I'd like to work on this.

**Comment by endymion1818** [comment]
Google doc for this article: https://docs.google.com/document/d/1Sspfv70vDPyvxIEWMScsdjalzfMpgEWfdc8bxDJ5c64/edit
