### ISSUE TITLE
Build a blog with Remix and Webiny Headless CMS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#16]

**Comment by asaayushisingh** [comment]
Hii @endymion1818 ,i'd like to work on this

**Comment by endymion1818** [comment]
@singhavs please could you submit your brief before Thursday by commenting below. Otherwise you could lose the opportunity to work on this article.

**Comment by IsaacThaJunior** [comment]
I'd love to write on this

**Comment by endymion1818** [comment]
Hi @IsaacThaJunior Thanks for your interest in this article! Could you submit a brief and outline by commenting below, then we can assess what your plan is and give you the go ahead or refine it before you start writing. Glad to have you on board!

**Comment by IsaacThaJunior** [comment]
This article will cover how to use Webiny Headless CMS and Remix to develop a blog application. 

Introduction
Prerequisites for following along
Understanding Webiny and why use Webiny
Understanding Remix and benefits of using Remix
Setting up Webiny Headless CMS
Creating models
Adding content
Setting up Roles and Permissions
Setting up Remix 
Installing Tailwind for styling purposes
Fetching data from Webiny
Conclusion

**Comment by swapnilmmane** [comment]
Hi @IsaacThaJunior, here is a [Notion document](https://www.notion.so/webiny/Build-a-blog-with-Remix-and-Webiny-Headless-CMS-2b36a5c0fbba4da69fceac7a06225b88) that you can use to manage the draft for your article, thank you!
