### ISSUE TITLE
How to implement Pagination with Webiny headless CMS in React

### ISSUE THREAD

**Issue by swapnilmmane** [webiny/write-with-webiny#2]

**Comment by Tammibriggs** [comment]
Hi @swapnilmmane, 

I am interested in this topic. Here is the outline:

Outline
- Introuduction Webiny headless CMS
- What is pagination
- Types of Paination
    - Offset-based pagintion
    - Cusor-based pagination
- Implemening Pagination with Webiny 
    - Setting up webiney
    - Populating our CMS with content
    - Implement offset-based pagination
    - Implement Cursor-based pagination
- Conclusion

**Comment by swapnilmmane** [comment]
Thank you @Tammibriggs, as discussed on Slack, happy to proceed with the topic. 
Assigning the issue to you, thanks!

**Comment by Tammibriggs** [comment]
Hi @swapnilmmane,

Sorry for the delay in submitting the article. I am done with it. 

Here is the link to it on Dropbox:
https://www.dropbox.com/scl/fi/b16zp8awj29pdli9cv1s8/How-to-implement-Pagination-with-Webiny-headless-CMS-in-React.paper?dl=0&rlkey=80k1lbp1as0tucq2gr7mnt1nl

**Comment by endymion1818** [comment]
Article published 🎉 https://www.webiny.com/blog/implement-pagination-webiny-headless-cms-react

**Comment by Tammibriggs** [comment]
@endymion1818 Thanks.
