### ISSUE TITLE
Building a Photo Gallery app with Webiny and Nuxt.js

### ISSUE THREAD

**Issue by miracleonyenma** [webiny/write-with-webiny#23]
### Introduction

Serverless infrastructure has many benefits when it comes to building modern applications. These benefits include lower latency, reduced costs, quicker deployments, and many more. With a serverless application framework like Webiny, we can build modern applications powered by serverless architecture.

In this tutorial, we're going to see how we can build a full-stack application by leveraging on Webiny as a Headless CMS.
We'll be building a Pinterest clone with Webiny and Nuxt 3, where users would be register and sign in to the app, create pins and view other pins created by other users.

We'll cover how Webiny works as a Serverless CMS and we'll walk through the process of creating, configuring, and deploying a Webiny project and with a GraphQL API. 
Then, we connect it to a Nuxt frontend with authentication, build out the functionality for creating and viewing pins.

### Goals

This article aims to introduce readers to the concept Headless CMS and creating applications with serverless infrastructure with Webiny. 

### Outline

In this article we'll cover the following main parts:

- Brief introduction to Serverless, Headless CMS
- What is Webiny
- Setting up and deploying a Webiny project
- Configuring the GraphQL API
- Headless CMS GraphQL API security layer
- Building CRUD endpoints
- Implementing authentication and authorization on the GraphQL API
- Setting up the front end 
- Building the CRUD functionality
- Conclusion
- Resources

I would like to submit this article as a tutorial.

### Sample articles

Here are a few

- [How To Implement Search Functionality In Your Nuxt App Using Algolia InstantSearch](https://www.smashingmagazine.com/2021/10/search-functionality-nuxt-app-algolia-instantsearch/)
- [Build a Link Previewer with Puppeteer and Serverless Functions](https://www.sitepoint.com/puppeteer-serverless-functions-link-previewer/)

**Comment by endymion1818** [comment]
Hey @miracleonyenma, how are you getting on with the article? Please let us know by Monday otherwise we will have to move it back to "looking for a writer"

**Comment by miracleonyenma** [comment]
Hey @endymion1818 !

Terribly sorry for not updating you on my progress.
I ran into some issues setting up Webiny on my machine. 

Fortunately, I managed to get it up and running last week and will be working the article this week ☺️.

Thanks for understanding 🙏🏾

**Comment by endymion1818** [comment]
Hi @miracleonyenma, no worries, glad you got it working! But also don't forget the [slack](https://www.webiny.com/slack) community is there to support you if you get stuck again!

**Comment by endymion1818** [comment]
Hi @miracleonyenma we need you to sign a freelance writer agreement with us, as a matter of urgency could you please contact me via Slack and we'll get you set up. Thanks!

**Comment by miracleonyenma** [comment]
Alright @endymion1818 

I just dropped a message on slack. 
I'm just responding now because I've been unavailable for the past week. I'm really sorry for any inconvenience it may have caused 🙇🏾‍♂️

**Comment by endymion1818** [comment]
No worries @miracleonyenma
