### ISSUE TITLE
Create a blog with Webiny and Svelte / SvelteKit

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#24]
### Introduction

Svelte is an efficient frontend framework and compiler that works using forward refs instead of a virtual DOM. Using SvelteKit as a static site generator for Webiny Headless CMS is a great choice for building a blog site.

### Goals

This article aims to instruct the user how to connect to Webiny and use it as a data source for a frontend built with Svelte and SvelteKit.

### Outline

We will cover:
- Brief introduction to Svelte and Webiny
- Installing a new SvelteKit site
- Setting up and deploying a Webiny project
- Authenticating with Webiny Headless CMS GraphQL API
- Fetching data for pages using Webiny Headless CMS
- Creating pages from API data
- Using the Preview API to fetch draft data
- Conclusion
- Resources

**Comment by Davidohis** [comment]
Hi Webiny, I am interested in writing on this topic.

Hope to get a response soon.

Regards.

**Comment by endymion1818** [comment]
Hi @Davidohis, great! Let's get you onboarded, I'll send you some things via DM in the Slack channel.
