### ISSUE TITLE
How to build a custom field plugin for Webiny Headless CMS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#26]
### Introduction

Webiny has been built with developer experience in mind. It's composable architecture makes it easy to create plugins to modify any part of the admin interface, the GraphQL resolvers, and the APIs.

### Goals

Create a new plugin to modify the admin interface by changing the logo.

### Outline

- Introduction: Why is composable architecture important in a CMS
- How to create a new plugin
- Creating a plugin for modifying the admin interface logo
- Conclusion

**Comment by endymion1818** [comment]
Hi @menard-codes! Yes, here are some docs on plugin creation: https://www.webiny.com/docs/core-development-concepts/basics/plugins

**Comment by menard-codes** [comment]
Thanks!
I already read the docs and it seems interesting to write. May I request this article?

**Comment by endymion1818** [comment]
@menard-codes Let's chat some more! I've sent you a message on our Slack community, chat to you there.
