### ISSUE TITLE
Build a blog with Gatsby and Webiny Headless CMS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#3]

**Comment by Dsalinasgardon** [comment]
Building a blog with Gatsby and Webiny Headless CMS

If you're a software developer and you want to create a blog, Gatsby is an excellent option. With Gatsby, you can use React to create your blog's frontend, and then use Webiny to manage your content. 

In this tutorial, I'll show you how to set up your Gatsby site and connect it with your Webiny account. I'll also walk you through the process of creating posts and pages in Webiny. 

Let's get started!

### What is Gatsby?
### Benefits of Gatsby for blogs
### Building a blog with Gatsby and Webiny
0. Prerequisites
A webiny project
- Basic GraphQL knowledge
- A working terminal or and code editor 
1.  Create your first content model
2. Manage content and create blog posts
3. Start Gatsby
4. Setting up a Gatsby blog
5. Pull GraphQL data into Gatsby
6. Preview your content

### Closing thoughts

**Comment by endymion1818** [comment]
Closing as we had another article that was materially identical to this one. It was nice to have an honest chat to you about this @Dsalinasgardon, looking forward to working together on something else soon!
