### ISSUE TITLE
How to implement Pagination in Vue.js with Webiny headless CMS 

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#30]
### Goals

We will build a simple list of paginated content using Vue.js and Webiny Headless CMS

### Outline

- Introduction
- How pagination works in Webiny Headless CMS APIs
- Paginating a Vue blog using next / previous
- Paginating a Vue blog with numbered pages
- Conclusion

**Comment by Tammibriggs** [comment]
Hi @endymion1818,

I am interested in writing this article.

**Comment by endymion1818** [comment]
Hi @Tammibriggs, I've just tested it and have a working example, here's my query, hope it helps!

```
    query PostSlugs($limit:Int) {
      listPosts(limit:$limit, sort: createdOn_ASC, after: "IjIi") { # the value of 'after' is the meta.cursor property
        meta {
          cursor
        }
        data {
          id
          title
        }
      }
    }
```

**Comment by Tammibriggs** [comment]
Hi @endymion1818,

I am aware the cursor-based pagination available using GraphQL API. But using this type of pagination, Paginating with numbered pages can't be implemented on the frontend.

**Comment by Tammibriggs** [comment]
Hi @endymion1818,

I will like to know how I should proceed with this.

**Comment by endymion1818** [comment]
Hi @Tammibriggs I've sent you a Notion page for this article via Slack. Reach out to me there if you get stuck with anything.
