### ISSUE TITLE
Build a CRUD To-do Application with Flutter and Webiny Headless CMS

### ISSUE THREAD

**Issue by kimkimani** [webiny/write-with-webiny#31]
### Introduction

Flutter is a multi-platform development toolkit. It allows you to build native applications that can be compiled and run on different platforms, such as Android, IOS, web, and desktop. This hugely speeds up mobile development workflow and promotes code reusability.

As a developer who wants to build a full-stack flutter application, you need a server to manage your data and consume it using Flutter. Webiny allows you to run a serverless headless CMS to model your application content. It then delivers a scalable GraphQL API to consume this data.

### Goals

In this guide, we will learn more about Webiny. We will model a CRUD To-Do content using its Headless CMS. Finally, build a Flutter fronted application to manage these to-dos.

### Outline
- What is a Headless CMS?
- Why use Webiny CMS?
- Prerequisites
- Setting up Webiny CMS
    - Content Structure
    - Connecting the CMS to the application
- Set up a Flutter application
- Build a To-Do app with Flutter
- Build Flutter widgets
- Perform To-Dos CRUD operations with Flutter
    - Create a To-Do Item
    - Add new To-Dousing Flutter UI
    - Update a To-Do
    - Delete a To-Do
- Conclusion

**Comment by UcFlutter** [comment]
I'd like to take the topic

**Comment by endymion1818** [comment]
Sorry @UcFlutter , this article is already taken, it would be great if you could choose another or suggest one!
