### ISSUE TITLE
Building GraphQL APIs in Go using  the GraphQLGen Package

### ISSUE THREAD

**Issue by Goodnessuc** [webiny/write-with-webiny#35]
### Introduction

There are many graphql packages in Go however, gqlgen is the most feature-rich and most used package for building GraphQL  APIs and servers in Go. The article will use a SQL database.

### Goals

We will be building a CRUD GraphQL API in Go using the GORM ORM package to connect to the SQL database.

### Outline

- Introduction
    - Why GraphQL
    - The packages
        - GORM
        - GQLGen
- Getting Started
    - Prerequisites
    - What will be built?
    - Installing and Import
- Database Setup(GORM + SQLite)
- GraphQL Schema Setup
    - Schema definition
    - Generate resolver
- Writing the caller functions
    - Create handler
    - Read handler
    - Update handler
    - Delete handler
- Testing the GraphQL API
- Conclusion

### Sample articles

https://www.makeuseof.com/go-sql-database-how/

https://earthly.dev/blog/introduction-pyscript/

https://blog.logrocket.com/ethereum-development-using-go-ethereum/

**Comment by endymion1818** [comment]
Hello @Goodnessuc, thanks very much for your submission! How does Webiny Headless CMS fit into this tutorial?
