### ISSUE TITLE
Create a Web3 Buy/Sell Button using JavaScript/solidity 

### ISSUE THREAD

**Issue by Scofield-Idehen** [webiny/write-with-webiny#43]
### Introduction

Creating a smart contract that can be deployed by clicking a button and allowing us to see and find the actual price of ETH to USD and we can buy a token.

### Goals

In this article, readers will learn how to integrate smart contracts in their front-end development and allow users to buy coins with a click of the button

### Outline

1. Introduction (Why is this topic important)
2. Create a smart contract using solidity
   - Using remix code editor
   - using a local code editor(vs code) 
3. Create a frontend button using JavaScript
   - Writing our structure, HTML, Tailwind CSS, 
4. Allow an API to get data from our solidity and show output
5. conclusion
6. Resources

### Sample articles

https://blog.logrocket.com/how-deploy-smart-contracts-iota/

**Comment by endymion1818** [comment]
Hi @Scofield-Idehen ! Thanks very much for your submission ... Web3 is a subject we're keen to cover. But I'm struggling to see how Webiny fits into this tutorial?

**Comment by Scofield-Idehen** [comment]
Ok, do I have to write something directly related to webiny, or majorly using key infrastructure specified on webiny?

**Comment by endymion1818** [comment]
Yes it does need to be directly related. I am looking for someone to explore whether Webiny can authenticate using MetaMask, if that's something you're interested in looking into?

**Comment by Scofield-Idehen** [comment]
I would be excited to work on that.

**Comment by Scofield-Idehen** [comment]
Hello, I have been researching the topic but do you have a base outline I should focus on, or do I have freedom to create however I please? 

Please clarify the topic name for me. 

Best regards.

**Comment by endymion1818** [comment]
Hi @Scofield-Idehen, let's chat more on our Slack channel about this!

**Comment by endymion1818** [comment]
Closing pending further research, thanks @Scofield-Idehen for your input!
