### ISSUE TITLE
[SUBMIT] Create a Job Board Application with Webiny, Vue & GraphQL

### ISSUE THREAD

**Issue by petipois** [webiny/write-with-webiny#58]
### Introduction

Job Board applications are a way for employers to advertise job vacancies to potential employees or freelancers. 

Job Board applications like Upwork, freelancer and other on company websites are a great way to advertise vacancies for potential talent to join their company or to complete a project. 

### Goals

 In this article, we will learn about the Webiny CMS and how we can use it in a Vue application by building a job Board application.

### Outline

 - Prequisites 
 - What will be build
 - Webiny CMS
- Admin section
 - Content Structure for Job Board
 - Creating content for the backend 
 - 
  - Building the frontend for the Job Board
 - Creating a Vue Application using Vite
- Laying out the application
- Connecting the CMS to the application
- GraphQl 
 - Adding Jobs
- Removing Jobs
  - Conclusion
  - Resources

**Comment by swapnilmmane** [comment]
Hi @petipois, thank you for the detailed outline. It looks nice. As a next step, I have sent you a statement of work to sign. 
Once that is signed, I will create a Notion document for you to write the article. 
Looking forward to collaborating with you, thanks!

**Comment by petipois** [comment]
Great, I will await the notification of the notion document.

**Comment by swapnilmmane** [comment]
Thank you @petipois, I have shared a Notion document with you. Please feel free to have a look at the instructions in it and use it for writing your draft.
Looking forward to your article! 🙌

**Comment by petipois** [comment]
Hello @swapnilmmane,
I have create a draft of the article on notion. I would be interested to have some feedback and comments on improvements. 
thank you
