### ISSUE TITLE
Build a Trello clone with NextJS and Webiny Headless CMS

### ISSUE THREAD

**Issue by endymion1818** [webiny/write-with-webiny#6]

**Comment by samarpit30** [comment]
I am interested in solving this issue.

**Comment by swapnilmmane** [comment]
Great, thank you @samarpit30 for your interest. I am assigning this issue to you.

**Comment by samarpit30** [comment]
Hi @swapnilmmane !
I am planning to include the following features in the application, and here is the brief.
## Application Features
### Board Management 
Create, Edit, and Delete a Board

### List Management 
Users can create, edit, and delete lists on a board

### Card Management 
Users can create, edit, delete cards and move them among the lists. 

![Trello](https://user-images.githubusercontent.com/42511743/181033035-84175d0e-44de-4afe-9a19-6f60f0d7aab0.png)

A Card will have a Title, Description, and Cover Image.
Users can move any card from one list to another by either editing it or dragging it from one list to another. 


Following is the list of features that will be included in the Trello clone app built with Next.js and Webiny.


## Here is the outline for the blog:

- Introduction (About the blog and technologies that will be used in it)
- About Webiny
- Setting up the Webiny Backend
- Setting up the Next.js frontend
- Adding the following features step by step, which include the UI on frontend and data management on the Backend
-- Create Board
-- Edit Board 
-- Delete Board
-- Create List
-- Edit List
-- Delete List
-- Create Card
-- Edit Card
-- Move Card in the list

**Comment by swapnilmmane** [comment]
Thank you @samarpit30, the abstract looks good to us, and happy for you to proceed with it! 👍
