### ISSUE TITLE
[SUBMIT] Create a Marketplace Application using Webiny & Apollo Vue

### ISSUE THREAD

**Issue by petipois** [webiny/write-with-webiny#68]
### Introduction

Marketplace applications are popular to advertise products for sale such as Ebay or Vinted. These applications are a great way to sell unwanted items. These items do not have to be restricted by physical items, they could also be courses or digitial products etc.  
Using Webiny CMS, and the power of content model with it's easy to navigate drag-n-drop style interface, will make this application easier to create, update and also remove certain items from the platform.

### Goals

Create a marketplace application using Webiny CMS

### Outline

  - Overview of Marketplace Application
  - Prerequisites
  - Webiny CMS and Vue Apollo
  -- Setting up Webiny CMS
    -- Content Structure
    -- Content Model
  - Building a Markeplace application
    -- View a list of Items
    -- Create new items
    -- Update Item
    -- Delete Item
  - Conclusion
  - Resources

### Sample articles

https://www.webiny.com/blog/build-job-board-application-vue-graphql

**Comment by endymion1818** [comment]
Awesome @petipois thanks so much this is great!
