### ISSUE TITLE
Integrating Reactjs Site with Webiny Headless CMS

### ISSUE THREAD

**Issue by Geo-free** [webiny/write-with-webiny#77]
### Introduction

In this tutorial, I will be taking the reader on how one sets up a CMS to a custom React Js site. I will not be going to build a CMS from scratch, instead, I would use Sanity - a headless CMS i.e, sanity.io, and just integrate it into a sample ReactJS application. I will set up a blog and then connect it to the ReactJS-based site, the front end.

Keep in mind that developers can use the same approach to integrate Sanity CMS into sites built using other web frameworks like Vue, PHP, and Angular.

### Goals

In this article, I will be showing the reader how to integrate a Headless CMS into a front-end React Js site. The knowledge gained here can be used by developers to integrate Headless CMS into any web framework such as Vue, PHP, and Angular.

### Outline

Here is the sample outline.
   - What are React Js websites
  - What is a Headless CMS?
  - Why use Webiny Headless CMS?
  - Building a React Js Site
  - Integrating Headless CMS to the site
  - Conclusion

### Sample articles

My previously written articles can be found on my portfolio [Section Engineering Education Program](https://www.section.io/engineering-education/authors/geoffrey-omukuba/)

**Comment by endymion1818** [comment]
Hello @Geo-free ! Thanks for your submission :-D

We're specifically looking for articles that feature [Webiny Headless CMS ](https://www.webiny.com/) for this program. And I'm afraid we've already got a number of articles featuring React. We'd be happy to hear any other suggestions you have for other technologies and different projects though.

**Comment by Geo-free** [comment]
Hello, what about this?
Building a static website with a .Net framework and Headless CMS

**Comment by endymion1818** [comment]
@Geo-free sorry my friend, .Net is not a technology we're focusing on just now.
