### ISSUE TITLE
Build a Todo Application in React.js and Webiny Headless CMS

### ISSUE THREAD

**Issue by swapnilmmane** [webiny/write-with-webiny#9]

**Comment by Victory-ET** [comment]
Hi @swapnilmmane 
I'll like to write on this topic. Here's the abstract

Build a Todo Application in React.js and Webiny CMS

Introduction

To-do applications are a way of organizing things to do or achieve in the form of a list. This list allows us to write down tasks, reprioritize tasks more efficiently, and manage them for increased productivity.


Goals

In this article, we will learn about the Webiny CMS and how we can use this in a React application by working on building a to-do app.


Outline
- What is a Headless CMS?
- Why use Webiny CMS?
- Building a To-do application?
    - Installing dependencies
    - Creating an input section
    - Add to-do list display
- Setting up Webiny CMS
    - Content Structure
    - Connecting the CMS to the application
- Creating, Updating, and Deleting to-dos
- Conclusion
- Resources

**Comment by Victory-ET** [comment]
Hi @swapnilmmane,

I'm done writing the draft for the article. Here is a [link to the draft](https://www.dropbox.com/scl/fi/pb44suummlth9mozihjel/Build-a-Todo-Application-in-React.js-and-Webiny-CMS.paper?dl=0&rlkey=mtad6l5b476l3j8u9909e877j) for the named article, written on Dropbox Paper.
