### ISSUE TITLE
Build An Ecommerce App with Vue.js and Pinia[SUBMIT]

### ISSUE THREAD

**Issue by olujerry** [webiny/write-with-webiny#96]
### Introduction

Ecommerce applications enable users to share and sell products online. In this tutorial, we will create an Ecommerce application to help an agricultural store market their products. Tailwind will be used to style the app, and Pinia, a state management library, will be used to create type safe Vue Stores.

### Goals

This article will go over the Webiny CMS and how to integrate it with your Vue.js application. We will employ:Vue.js using Vite, GraphQL, Tailwind CSSand     Pinia

### Outline

[Here is the sample outline.
  - What is a Headless CMS?
  - Why use Webiny CMS?
  - Building an Ecommerce application?
    -- Installing dependencies
   Create a New Webiny Project
   Creating Categories
   Creating Sellers Model
   Creating the Products Model
   Creating Our Vue Application
   Adding Vue Router
    Adding Tailwind CSS
    Environment Variables
    State Management With Pinia
    Sellers Model
    The Shopping Cart
     Creating New Products
  - Conclusion
  - Resources]

### Sample articles

https://strapi.io/blog/how-to-build-a-to-do-app-using-next-js-and-strapi-1

https://medium.com/p/d3cbef264ce4

  https://medium.com/p/644db0795edf

**Comment by Davidohis** [comment]
Hi @endymion1818, I am interested in writing on this topic. 

Hope to get a response soon.

Regards.

**Comment by endymion1818** [comment]
Thanks for your submission @olujerry, we've just had a very similar article published, please feel free to suggest something else!
